Refactor sidebar to use the new style
multinet-app/multilink pull request #140
Opened 2021-01-05 17:03 UTC by JackWilb

2021-01-05 17:42 UTC, jtomeck requested changes
This looks really good. The only thing I'd like to see is better hierarchy of the action buttons (start, stop, release, export). To me, start and stop seem like the main simulation controls, while "release pinned nodes" seems like you're just clearing what you have selected. I think those 3 buttons should be paired together, with "export" as the main and final action below them.

I suggest we do the following:
- Simplify the wording of the buttons to "Start," "Stop," and "Release Pinned."
- Add play icon to start, stop icon to stop, and either `mdi-pin-off` or `mdi-debug-step-out` to release pinned.
- Right align "Start" and "Stop" side-by-side
- Left align "Release Pinned" on the other side of "Start" and "Stop" (this might require you to use a smaller size prop for the buttons)
- Keep "Start" and "Stop" the primary color with the `depressed` prop, but give "Release Pinned" the `text` prop and maybe make it `grey darken-3`
- Keep the export button below the 3 other buttons, full width, `depressed`, and `grey darken-3`

I think this would help the action buttons portion. Let me know what you think.

2021-01-05 20:23 UTC, jtomeck approved these changes

2021-01-06 16:45 UTC, waxlamp approved these changes
Looks good. We should explore whether to integrate the start and stop buttons into a single button that changes state when clicked, but this looks great at the moment. Thanks @JackWilb and @jtomeck!

2021-01-06 16:47 UTC, JackWilb commented
> Looks good. We should explore whether to integrate the start and stop buttons into a single button that changes state when clicked, but this looks great at the moment. Thanks @JackWilb and @jtomeck!



> Looks good. We should explore whether to integrate the start and stop buttons into a single button that changes state when clicked, but this looks great at the moment. Thanks @JackWilb and @jtomeck!

Good idea. I opened #141

2021-01-06 16:47 UTC, merged