alert-dropdowns
multinet-app/multilink pull request #205
Opened 2021-02-27 01:53 UTC by JackWilb

2021-03-01 16:58 UTC, waxlamp requested changes
- Change `graph` to `network`
- When the app is loaded without having specified a network, it should not behave as though something is wrong; instead, it should show a gentler message with the dropdowns directing the user to pick a workspace and network
- The CORS error scenario looks ok to me
- This is a case where it is more or less *required* to get @jtomeck's opinion on things--this is UX bread and butter and it's a mistake for us to proceed here without his expertise in the loop. I'd like for him to do a design review here, including getting an understanding of the problem we're trying to solve.

2021-03-01 17:06 UTC, JackWilb commented
Requested a review from @jtomeck. I'll wait for his feedback before I start addressing your points @waxlamp

2021-03-01 17:13 UTC, jtomeck requested changes
1. I think on the alerts with dropdowns, the vertical padding is a little too much.
2. I also think adding instructions under the alert text in non-bold font like "select a workspace or network you'd like to return to."
    - I think this also begs the question of why they're getting a "not found" error. Could that be a permissions issue? Maybe some text saying to contact the workspace owner or review permissions would be good here.
3. Can we also add the `tile` prop to the alert? It doesn't need rounded corners since it's flush to the edge.

2021-03-02 21:21 UTC, JackWilb commented
Here are all of the possible states:

Parameters missing from query:
![image](https://user-images.githubusercontent.com/36867477/109716475-2c966f80-7b62-11eb-9296-d319f83a7fd3.png)

Unauthorized:
![image](https://user-images.githubusercontent.com/36867477/109716548-3f10a900-7b62-11eb-83a5-45ab91f78dca.png)

Graph not found:
![image](https://user-images.githubusercontent.com/36867477/109716610-52bc0f80-7b62-11eb-8913-3ce47efe99f6.png)

Workspace not found:
![image](https://user-images.githubusercontent.com/36867477/109716679-610a2b80-7b62-11eb-9734-161b8ea52aa9.png)

CORS error (any networking issue):
![image](https://user-images.githubusercontent.com/36867477/109716792-7ed79080-7b62-11eb-9c7e-17d0fa8469a3.png)

2021-03-10 21:04 UTC, jtomeck commented on src/components/Alert.vue
> +      type="error"
```suggestion
      type="warning"
      outlined
      text
      border="left"
```

Roni mentioned in his comment that a softer message would be better and I think a softer color for the alert would probably be better as well.

2021-03-10 21:05 UTC, jtomeck commented on src/components/Alert.vue
> +          <v-btn :href="buttonHref">
```suggestion
          <v-btn
              :href="buttonHref"
              depressed
          >
```

2021-03-10 21:06 UTC, jtomeck requested changes
This is looking great, I added a couple code suggestions, but after that I think we're good.

2021-03-10 23:44 UTC, jtomeck approved these changes, later dismissed

2021-03-11 16:41 UTC, JackWilb commented
Here's the final design after a couple iterations with @jtomeck on slack.

2021-03-11 16:43 UTC, waxlamp requested changes
This is looking great!

One big thing: this still uses the word "graph"--that needs to be "network".

2021-03-11 16:47 UTC, JackWilb commented
>One big thing: this still uses the word "graph"--that needs to be "network".

@waxlamp "Graph not found" comes from tha API. Instead of putting in custom logic here to change it, we should just fix it there

2021-03-11 16:48 UTC, waxlamp approved these changes

2021-03-11 16:54 UTC, merged